---
multiple_civica:
  description: Scrapes multiple authorities with the civica system
  last_updated: '2024-07-16T06:34:38.582Z'
multiple_icon:
  description: Scrapes multiple authorities that have an icon system
  last_updated: '2024-07-16T06:25:11.091Z'
multiple_epathway_scraper:
  description: Scrape multiple authorities with epathway scraper
  last_updated: '2024-07-16T06:15:56.575Z'
multiple_masterview:
  description: Scrapes multiple authorities that have a masterview system
  last_updated: '2024-07-16T05:07:10.771Z'
multiple_technology_one:
  description: Scrapes multiple authorities using technology one system
  last_updated: '2024-07-16T03:59:35.738Z'
multiple_horizon:
  description: Scrapes multiple authorities with the horizon system
  last_updated: '2023-09-12T01:51:12.391Z'
multiple_cianywhere:
  description: ''
  last_updated: '2023-09-11T07:25:59.939Z'
multiple_developmenti:
  description: Scrape multiple authorities using the development.i system
  last_updated: '2023-09-11T01:05:33.860Z'
multiple_atdis:
  description: Scrapes multiple authorities that have ATDIS feed
  last_updated: '2023-01-31T00:50:00.136Z'
multiple_greenlight:
  description: Scrape councils using the greenlight OPM system
  last_updated: '2022-07-25T05:06:55.402Z'

